with seed as (
  select *
  from jsonb_to_recordset(
    $json$
    [
      {"id":"d1563bc9-95d1-560d-ad19-f64adeeae147","slug":"hello","english_word":"Hello","urdu_word":"ہیلو","category":"Sentences","external_url":"https://psl.org.pk/dictionary/65-sentences/4309-hello","review_status":"verified","is_active":true,"sort_order":1},
      {"id":"c8fc7682-ba1a-5eac-953b-6591660e3541","slug":"assalam-o-alaikum","english_word":"Assalam-o-Alaikum","urdu_word":"السلام علیکم","category":"Sentences","external_url":"https://psl.org.pk/dictionary/65-sentences/4268-assalam-o-alaikum","review_status":"verified","is_active":true,"sort_order":2},
      {"id":"4facda7b-f115-58f9-819e-1ebb67e88231","slug":"thankyou","english_word":"Thank You","urdu_word":"شکریہ","category":"Sentences","external_url":"https://psl.org.pk/dictionary/65-sentences/4369-thank-you","review_status":"needs_review","is_active":true,"sort_order":3},
      {"id":"49bc7bcc-eb68-5435-b666-58f5c7b7b4a5","slug":"nothing","english_word":"Nothing","urdu_word":"کچھ نہیں","category":"General","external_url":null,"review_status":"needs_review","is_active":true,"sort_order":4},
      {"id":"c7a95ce1-013d-5669-babc-9397d3ff0e5b","slug":"goodbye","english_word":"Goodbye","urdu_word":"خدا حافظ","category":"Sentences","external_url":"https://psl.org.pk/dictionary/65-sentences/4305-goodbye","review_status":"verified","is_active":true,"sort_order":5},
      {"id":"33822a02-e797-5a71-912d-1a1286678ecc","slug":"excuseme","english_word":"Excuse Me","urdu_word":"معاف کیجیے","category":"Sentences","external_url":"https://psl.org.pk/dictionary/65-sentences/4299-excuse-me","review_status":"needs_review","is_active":true,"sort_order":6},
      {"id":"b0ec6b50-cde9-5b51-9c7e-6d1178db4bbf","slug":"water","english_word":"Water","urdu_word":"پانی","category":"Drinks","external_url":"https://psl.org.pk/dictionary/31-drinks/7070-water","review_status":"needs_review","is_active":true,"sort_order":7},
      {"id":"10133445-f3fc-5e71-bf8f-055fbaa4bc34","slug":"bring","english_word":"Bring","urdu_word":"لے آؤ","category":"Verbs","external_url":"https://psl.org.pk/dictionary/72-verbs/4871-bring","review_status":"verified","is_active":true,"sort_order":8},
      {"id":"65b8deef-2664-5ad7-aa50-92b2d1dbaea8","slug":"airplane","english_word":"Airplane","urdu_word":"ہوائی جہاز","category":"Airport","external_url":"https://psl.org.pk/dictionary/3-airport/162-airplane","review_status":"needs_review","is_active":true,"sort_order":9},
      {"id":"43052f8f-4991-5daf-bb51-b2b75125e367","slug":"donttouch","english_word":"Don't Touch","urdu_word":"ہاتھ نہ لگاؤ","category":"Sentences","external_url":"https://psl.org.pk/dictionary/65-sentences/4297-don-t-touch","review_status":"needs_review","is_active":true,"sort_order":10},
      {"id":"3c16a252-f80e-54a1-8ee3-d5ae748aa594","slug":"fan","english_word":"Fan","urdu_word":"پنکھا","category":"Around The House","external_url":"https://psl.org.pk/dictionary/10-around-the-house/415-fan","review_status":"verified","is_active":true,"sort_order":11},
      {"id":"261e666e-49bb-57b2-9092-6d0dd06fefda","slug":"bench","english_word":"Bench","urdu_word":"بنچ","category":"Around The House","external_url":"https://psl.org.pk/dictionary/10-around-the-house/406-bench","review_status":"needs_review","is_active":true,"sort_order":12},
      {"id":"07069d78-d062-554c-a394-f7cb3fb93a08","slug":"have_a_good_day","english_word":"Have a Good Day","urdu_word":"آپ کا دن اچھا گزرے","category":"Service Phrases","external_url":"https://psl.org.pk/dictionary/81-kfc/6740-have-a-good-day!","review_status":"needs_review","is_active":true,"sort_order":13},
      {"id":"facfef14-0447-5320-b595-5c9202faeaba","slug":"we","english_word":"We","urdu_word":"ہم","category":"Pronouns","external_url":"https://psl.org.pk/dictionary/63-pronouns/4123-we","review_status":"needs_review","is_active":true,"sort_order":14},
      {"id":"1cc787fb-378f-55fb-acd6-9a6b5dd1fa00","slug":"you","english_word":"You","urdu_word":"آپ","category":"Pronouns","external_url":"https://psl.org.pk/dictionary/63-pronouns/4124-you","review_status":"verified","is_active":true,"sort_order":15},
      {"id":"9f4da1a5-84b1-5053-9140-4dba3917e49d","slug":"door","english_word":"Door","urdu_word":"دروازہ","category":"Around The House","external_url":"https://psl.org.pk/dictionary/10-around-the-house/412-door","review_status":"verified","is_active":true,"sort_order":16},
      {"id":"3366586f-4996-50b1-a876-2cb927c47ccb","slug":"garden","english_word":"Garden","urdu_word":"باغ","category":"Around The House","external_url":"https://psl.org.pk/dictionary/10-around-the-house/421-garden","review_status":"needs_review","is_active":true,"sort_order":17},
      {"id":"eb060010-e548-58a2-966f-03deba6bccde","slug":"mine","english_word":"Mine","urdu_word":"میرا","category":"Pronouns","external_url":"https://psl.org.pk/dictionary/63-pronouns/4106-mine","review_status":"needs_review","is_active":true,"sort_order":18},
      {"id":"acbf52ff-cb07-5540-a083-f9a399130990","slug":"absolutely","english_word":"Absolutely","urdu_word":"بالکل","category":"Adverbs","external_url":"https://psl.org.pk/dictionary/2-adverbs/209-absolutely","review_status":"needs_review","is_active":true,"sort_order":19},
      {"id":"13945af3-8368-5f46-ae85-13c11c4af852","slug":"all","english_word":"All","urdu_word":"سب","category":"Pronouns","external_url":"https://psl.org.pk/dictionary/63-pronouns/4092-all","review_status":"verified","is_active":true,"sort_order":20},
      {"id":"d40845dc-b86d-57a3-8029-72bb031ec6a3","slug":"both","english_word":"Both","urdu_word":"دونوں","category":"Pronouns","external_url":"https://psl.org.pk/dictionary/63-pronouns/4096-both","review_status":"verified","is_active":true,"sort_order":21},
      {"id":"d14d00b3-ab15-576a-927d-39403473f7ff","slug":"bulb","english_word":"Bulb","urdu_word":"بلب","category":"Around The House","external_url":null,"review_status":"needs_review","is_active":true,"sort_order":22},
      {"id":"bbefdb6a-ef94-5275-928d-29bfa88f1b51","slug":"mobile_phone","english_word":"Mobile Phone","urdu_word":"موبائل فون","category":"Appliances","external_url":"https://psl.org.pk/dictionary/9-appliances/296-mobile-phone","review_status":"verified","is_active":true,"sort_order":23},
      {"id":"beffa09f-33f0-5c39-823e-79396da57787","slug":"generator","english_word":"Generator","urdu_word":"جنریٹر","category":"Appliances","external_url":"https://psl.org.pk/dictionary/9-appliances/292-generator","review_status":"verified","is_active":true,"sort_order":24},
      {"id":"99bfffa6-e60a-5293-973d-38c896a217b9","slug":"aircrash","english_word":"Air Crash","urdu_word":"طیارہ حادثہ","category":"Airport","external_url":"https://psl.org.pk/dictionary/3-airport/161-air-crash","review_status":"verified","is_active":true,"sort_order":25},
      {"id":"6f7976dc-e996-5a39-b063-3249541d7d23","slug":"goodmorning","english_word":"Good Morning","urdu_word":"صبح بخیر","category":"Sentences","external_url":"https://psl.org.pk/dictionary/65-sentences/4303-good-morning","review_status":"verified","is_active":true,"sort_order":26},
      {"id":"689b7034-22a9-580a-ac97-f86f6c0f81c0","slug":"welldone","english_word":"Well Done","urdu_word":"شاباش","category":"Sentences","external_url":"https://psl.org.pk/dictionary/65-sentences/4381-well-done!","review_status":"verified","is_active":true,"sort_order":27},
      {"id":"4ef35b4c-69bb-521d-afdf-6cf8719c37ae","slug":"ihaveacomplaint","english_word":"I Have a Complaint","urdu_word":"مجھے شکایت ہے","category":"Service Phrases","external_url":"https://psl.org.pk/dictionary/81-kfc/6741-i-have-an-complaint","review_status":"verified","is_active":true,"sort_order":28},
      {"id":"35db74f3-4d40-5cbe-b492-75c308bb414f","slug":"bear","english_word":"Bear","urdu_word":"ریچھ","category":"Mammals","external_url":"https://psl.org.pk/dictionary/51-mammals/2847-bear","review_status":"verified","is_active":true,"sort_order":29},
      {"id":"8c42cc7e-a29c-5249-a518-69f3e52b35e2","slug":"cow","english_word":"Cow","urdu_word":"گائے","category":"Mammals","external_url":"https://psl.org.pk/dictionary/51-mammals/2857-cow","review_status":"verified","is_active":true,"sort_order":30},
      {"id":"5e834724-dd97-5e85-9253-67b2040f2c21","slug":"deer","english_word":"Deer","urdu_word":"ہرن","category":"Mammals","external_url":"https://psl.org.pk/dictionary/51-mammals/2859-deer","review_status":"needs_review","is_active":true,"sort_order":31},
      {"id":"93f85451-62e5-5f1f-b1e3-b07792b987bd","slug":"chimpanzee","english_word":"Chimpanzee","urdu_word":"چمپینزی","category":"Mammals","external_url":"https://psl.org.pk/dictionary/51-mammals/2854-chimpanzee","review_status":"verified","is_active":true,"sort_order":32},
      {"id":"ebcc9323-5b9b-5ed6-bd0d-ff240fbd4732","slug":"elephant","english_word":"Elephant","urdu_word":"ہاتھی","category":"Mammals","external_url":"https://psl.org.pk/dictionary/51-mammals/2863-elephant","review_status":"verified","is_active":true,"sort_order":33},
      {"id":"0a9dd277-b40a-5ca8-8924-f8620e6d01bd","slug":"dog","english_word":"Dog","urdu_word":"کتا","category":"Mammals","external_url":"https://psl.org.pk/dictionary/51-mammals/2861-dog","review_status":"verified","is_active":true,"sort_order":34},
      {"id":"e10b26a8-053f-5ab1-b782-f182cc1f88ff","slug":"policecar","english_word":"Police Car","urdu_word":"پولیس گاڑی","category":"Transport","external_url":"https://psl.org.pk/dictionary/70-transport/4706-police-car","review_status":"needs_review","is_active":true,"sort_order":35},
      {"id":"9656cd6c-46fe-55c0-85dc-7d4ffe1085ad","slug":"bicycle","english_word":"Bicycle","urdu_word":"سائیکل","category":"Transport","external_url":"https://psl.org.pk/dictionary/70-transport/4644-bicycle","review_status":"verified","is_active":true,"sort_order":36},
      {"id":"a68d091b-f640-532a-a0ec-ac956f5708b5","slug":"bridge","english_word":"Bridge","urdu_word":"پل","category":"Transport","external_url":"https://psl.org.pk/dictionary/70-transport/4646-bridge","review_status":"needs_review","is_active":true,"sort_order":37},
      {"id":"5bd1200d-dea5-5f18-b963-fd82324bc5e9","slug":"cartoon","english_word":"Cartoon","urdu_word":"کارٹون","category":"Arts","external_url":"https://psl.org.pk/dictionary/11-arts/435-cartoon","review_status":"verified","is_active":true,"sort_order":38},
      {"id":"f72ba3ce-5bb2-5810-80cd-6dbfb33abed4","slug":"color_pencils","english_word":"Color Pencils","urdu_word":"رنگین پنسلیں","category":"Arts","external_url":"https://psl.org.pk/dictionary/11-arts/439-colored-pencils","review_status":"needs_review","is_active":true,"sort_order":39},
      {"id":"8f04bc3b-24f6-51d1-96e8-74a2081c6256","slug":"atm","english_word":"ATM","urdu_word":"اے ٹی ایم","category":"Banking","external_url":"https://psl.org.pk/dictionary/12-banking/576-atm-automated-teller-machine","review_status":"needs_review","is_active":true,"sort_order":40},
      {"id":"0e77ac10-615d-5dd2-b2dd-a62fbe4b5ef5","slug":"nailcutter","english_word":"Nail Cutter","urdu_word":"نیل کٹر","category":"Bathroom","external_url":"https://psl.org.pk/dictionary/13-bathroom/560-nail-cutter","review_status":"verified","is_active":true,"sort_order":41},
      {"id":"3d1f3333-fe12-58f1-b3d9-cff93f58b6b1","slug":"shampoo","english_word":"Shampoo","urdu_word":"شیمپو","category":"Bathroom","external_url":"https://psl.org.pk/dictionary/13-bathroom/564-shampoo","review_status":"needs_review","is_active":true,"sort_order":42},
      {"id":"e8c4e5c9-1db2-5f16-abca-8e420cf3a3e8","slug":"razor","english_word":"Razor","urdu_word":"استرا","category":"Bathroom","external_url":"https://psl.org.pk/dictionary/13-bathroom/563-razor","review_status":"needs_review","is_active":true,"sort_order":43},
      {"id":"0db6d113-4c5e-5901-880a-28e54e5aa707","slug":"shower","english_word":"Shower","urdu_word":"شاور","category":"Bathroom","external_url":"https://psl.org.pk/dictionary/13-bathroom/565-shower","review_status":"needs_review","is_active":true,"sort_order":44},
      {"id":"734c8061-150c-52d7-a053-45f8b51dee48","slug":"tissue","english_word":"Tissue Paper","urdu_word":"ٹشو پیپر","category":"Bathroom","external_url":"https://psl.org.pk/dictionary/13-bathroom/569-tissue-paper","review_status":"verified","is_active":true,"sort_order":45},
      {"id":"2ff612bf-6772-5259-86b7-e835e6183dd6","slug":"toothbrush","english_word":"Toothbrush","urdu_word":"ٹوتھ برش","category":"Bathroom","external_url":"https://psl.org.pk/dictionary/13-bathroom/572-toothbrush","review_status":"verified","is_active":true,"sort_order":46},
      {"id":"bb3cc25d-06e5-5c43-9955-c13e8ce05cbc","slug":"toothpaste","english_word":"Toothpaste","urdu_word":"ٹوتھ پیسٹ","category":"Bathroom","external_url":"https://psl.org.pk/dictionary/13-bathroom/573-toothpaste","review_status":"verified","is_active":true,"sort_order":47},
      {"id":"6d119c40-1599-54c1-907d-833f45fdc668","slug":"sunglasses","english_word":"Sunglasses","urdu_word":"دھوپ کا چشمہ","category":"Beach","external_url":"https://psl.org.pk/dictionary/14-beach/623-sunglasses","review_status":"needs_review","is_active":true,"sort_order":48},
      {"id":"083821c3-0fbe-55f7-ac78-7699a92e3981","slug":"beach","english_word":"Beach","urdu_word":"ساحل","category":"Beach","external_url":"https://psl.org.pk/dictionary/14-beach/609-beach","review_status":"needs_review","is_active":true,"sort_order":49},
      {"id":"6c2074c8-bc43-51d9-90ad-ec466ec2e060","slug":"lifejacket","english_word":"Life Jacket","urdu_word":"لائف جیکٹ","category":"Beach","external_url":"https://psl.org.pk/dictionary/14-beach/612-life-jacket","review_status":"verified","is_active":true,"sort_order":50},
      {"id":"625d8cad-ad8c-57f7-91ec-e2b118cabcec","slug":"bald","english_word":"Bald","urdu_word":"گنجا","category":"Beauty","external_url":"https://psl.org.pk/dictionary/15-beauty/631-bald","review_status":"needs_review","is_active":true,"sort_order":51},
      {"id":"9c0d1479-16e5-5691-baa8-7c9892d07fe7","slug":"beard","english_word":"Beard","urdu_word":"داڑھی","category":"Beauty","external_url":"https://psl.org.pk/dictionary/15-beauty/633-beard","review_status":"needs_review","is_active":true,"sort_order":52},
      {"id":"91d5e2b4-29e8-58f9-9bff-936647ac5064","slug":"facelotion","english_word":"Face Lotion","urdu_word":"فیس لوشن","category":"Beauty","external_url":"https://psl.org.pk/dictionary/15-beauty/650-face-lotion","review_status":"verified","is_active":true,"sort_order":53},
      {"id":"c3469749-04ca-5a7c-8feb-5e7d852db77e","slug":"also","english_word":"Also","urdu_word":"بھی","category":"Adverbs","external_url":"https://psl.org.pk/dictionary/2-adverbs/212-also","review_status":"needs_review","is_active":true,"sort_order":54},
      {"id":"7571e9f7-da4b-5059-b407-91e7c055aaa6","slug":"bed","english_word":"Bed","urdu_word":"بستر","category":"Bedroom","external_url":"https://psl.org.pk/dictionary/16-bedroom/717-bed","review_status":"needs_review","is_active":true,"sort_order":55},
      {"id":"844b90bd-b5b7-53a0-befd-05c664172e7e","slug":"cupboard","english_word":"Cupboard","urdu_word":"الماری","category":"Bedroom","external_url":"https://psl.org.pk/dictionary/16-bedroom/725-cupboard","review_status":"needs_review","is_active":true,"sort_order":56},
      {"id":"e0425dc6-96d1-5aba-a5c6-930b42a2ef89","slug":"beak","english_word":"Beak","urdu_word":"چونچ","category":"Birds","external_url":"https://psl.org.pk/dictionary/17-birds/739-beak","review_status":"needs_review","is_active":true,"sort_order":57},
      {"id":"dc95c951-8c70-5e02-b217-cfcc082ee4f9","slug":"crow","english_word":"Crow","urdu_word":"کوا","category":"Birds","external_url":"https://psl.org.pk/dictionary/17-birds/742-crow","review_status":"needs_review","is_active":true,"sort_order":58},
      {"id":"c2351245-99af-5870-8610-682a775792db","slug":"peacock","english_word":"Peacock","urdu_word":"مور","category":"Birds","external_url":"https://psl.org.pk/dictionary/17-birds/761-peacock","review_status":"verified","is_active":true,"sort_order":59},
      {"id":"1ccbc4b5-5fc8-591f-93ab-404326af2632","slug":"arrival","english_word":"Arrival","urdu_word":"آمد","category":"Airport","external_url":"https://psl.org.pk/dictionary/3-airport/163-arrival","review_status":"needs_review","is_active":true,"sort_order":60},
      {"id":"7b9ea3d1-bec5-53a8-97f7-07d7a69e444e","slug":"umbrella","english_word":"Umbrella","urdu_word":"چھتری","category":"Beach","external_url":"https://psl.org.pk/dictionary/14-beach/628-umbrella","review_status":"verified","is_active":true,"sort_order":61},
      {"id":"92baf74a-2b3c-5a1c-b3d0-61a00535e24a","slug":"left_hand","english_word":"Left Hand","urdu_word":"بایاں ہاتھ","category":"Body","external_url":null,"review_status":"needs_review","is_active":true,"sort_order":62}
    ]
    $json$::jsonb
  ) as x(
    id uuid,
    slug text,
    english_word text,
    urdu_word text,
    category text,
    external_url text,
    review_status text,
    is_active boolean,
    sort_order integer
  )
)
insert into public.dictionary_entries (
  id,
  slug,
  english_word,
  urdu_word,
  category,
  external_url,
  review_status,
  is_active,
  sort_order
)
select
  id,
  slug,
  english_word,
  urdu_word,
  category,
  external_url,
  review_status,
  is_active,
  sort_order
from seed
on conflict (slug) do update
set
  english_word = excluded.english_word,
  urdu_word = excluded.urdu_word,
  category = excluded.category,
  external_url = excluded.external_url,
  review_status = excluded.review_status,
  is_active = excluded.is_active,
  sort_order = excluded.sort_order,
  updated_at = timezone('utc', now());
